import CDP from 'chrome-remote-interface';
import fs from 'fs';
const client = await CDP();
const {Page, Runtime, Emulation} = client;
await Runtime.enable(); await Page.enable();
await Emulation.setDeviceMetricsOverride({width:1000,height:1400,deviceScaleFactor:1,mobile:false});
await Page.navigate({url:'http://localhost:8140/'});
await new Promise(r=>setTimeout(r,1200));
await Runtime.evaluate({expression:`(async()=>{const rs=await navigator.serviceWorker.getRegistrations();for(const r of rs)await r.unregister();const ks=await caches.keys();for(const k of ks)await caches.delete(k);return rs.length})()`,awaitPromise:true});
await Page.navigate({url:'http://localhost:8140/font-samples.html'});
await new Promise(r=>setTimeout(r,3000));
await Runtime.evaluate({expression:'document.fonts.ready.then(()=>1)',awaitPromise:true});
await new Promise(r=>setTimeout(r,4000));
const info=(await Runtime.evaluate({expression:`JSON.stringify({sheets:[...document.styleSheets].map(s=>(s.href||'inline').slice(0,50)), loaded:[...new Set([...document.fonts].filter(f=>f.status==='loaded').map(f=>f.family))]})`,returnByValue:true})).result.value;
console.log(info);
const h=(await Runtime.evaluate({expression:'document.body.scrollHeight',returnByValue:true})).result.value;
console.log('h=',h);
await Emulation.setDeviceMetricsOverride({width:1000,height:h+40,deviceScaleFactor:1.5,mobile:false});
await new Promise(r=>setTimeout(r,1200));
const shot=await Page.captureScreenshot({format:'png'});
fs.writeFileSync('/tmp/font-samples.png',Buffer.from(shot.data,'base64'));
console.log('saved');
await client.close();
